[target.i686-sel4-robigalia.dependencies]
alloc = {}

[target.x86_64-sel4-robigalia.dependencies]
alloc = {}

# [target.i686-sel4-robigalia.dependencies.std]
# features = ["jemalloc"]

# [target.x86_64-sel4-robigalia.dependencies.std]
# features = ["jemalloc"]
